### ISSUE TITLE
AttendanceCodes endpoint doesn't have meta data

### ISSUE THREAD

**Issue by mikecmpbll** [wondeltd/ruby-client#6]
This causes the iterator to fail because it looks for `self.meta.pagination.more` https://github.com/wondeltd/ruby-client/blob/master/lib/resultiterator.rb#L24

```ruby
c = Wonde::Client.new("...")
c.attendanceCodes.all.each do |ac|
  puts ac.code
end
# exceptions after last code (tries to see if there's another page)
```

I'm not sure whether you intend to fix this on the API side (by including meta information on the attendance-codes endpoint), or in this library. I looked at your PHP sdk to see if it handled it differently but it looks as though the same issue might be present there?

I'm happy to provide a PR if you think it should be fixed in here.

**Comment by mikecmpbll** [comment]
(as an aside: should the attendance codes be a resource under the school? oftentimes schools have different attendance codes)

**Comment by Hodglim** [comment]
Hi Mike!

Thanks for your feedback and sorry for the late response (this has just been brought to my attention).

This should definitely be handled in the library so please feel free to submit your PR if you are still happy to do so.  The PHP library handles this by simply checking for the presence of the pagination object here (https://github.com/wondeltd/php-client/blob/master/src/ResultIterator.php#L55)

I noticed that you have also added support for Medical Notes which I would also be happy to merge.

Many thanks!
